version: "3.9"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/


  klangrausch_django:
    image: django_alpine3.16:3.2.18
    env_file:
      - .env.klangrausch.django
    volumes:
      - ../django/klangrausch/:/klangrausch/
    command: uvicorn klangrausch.asgi:application --host 0.0.0.0
  

  klangrausch_postgresql:
    image: postgres:alpine3.17
    env_file:
      - .env.klangrausch.postgresql


  klangrausch_gulp:
    image: gulp_node_alpine:18.14.2
    volumes:
      - ../gulp/klangrausch/:/klangrausch/
  #     - ../statifiles/css/:/staticfiles/css/
  #     - ../statifiles/js/:/staticfiles/js/
  #     - ../statifiles/img/:/staticfiles/img/
  #   command: "watch"
