version: "3"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    networks:
      klangrausch_development_network:
        ipv4_address: 172.16.77.11


  klangrausch_django:
    build:
      context: ../django/
      dockerfile: django.development.Dockerfile
    env_file:
      - .env.klangrausch_django
    volumes:
      - ../django/klangrausch/:/klangrausch/
    networks:
      klangrausch_development_network:
        ipv4_address: 172.16.77.12

  
  klangrausch_postgresql:
    image: postgres:11-alpine
    env_file:
      - .env.klangrausch_postgresql
    networks:
      klangrausch_development_network:
        ipv4_address: 172.16.77.13


networks:
  klangrausch_development_network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.77.0/24
