version: "3.9"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/
      - ../staticfiles/:/staticfiles/


  klangrausch_django:
    image: django_4.2.7_alpine3.18:python_3.10.12
    # ports:
    #   - "80:8000"
    env_file:
      - .env.klangrausch
    volumes:
      - ../django/klangrausch/:/klangrausch/
      - ../staticfiles/:/staticfiles/
    command: python manage.py runserver 0.0.0.0:8000
  

  klangrausch_postgresql:
    image: postgres:alpine3.17
    env_file:
      - .env.klangrausch
  

  # klangrausch_webpack:
  #   image: webpack_5:node_18.14.2-alpine3.17
  #   tty: true
  #   volumes:
  #     - ../webpack/webpack_5/:/klangrausch_webpack_5
  #     - ../staticfiles/css/:/files/staticfiles/css/
  #     - ../staticfiles/js/:/files/staticfiles/js/
  #     - ../staticfiles/img/:/files/staticfiles/img/
  #
