version: "3"

services:

  klangrausch_nginx:
    build:
      context: ../
      dockerfile: nginx.development.Dockerfile
    networks:
      klangrausch_network_development:
        ipv4_address: 172.16.77.10


  klangrausch_django:
    build:
      context: ../
      dockerfile: django.development.Dockerfile
      env_file:
        - .env.klangrausch_django
      networks:
        ipv4_address: 172.16.77.11


networks:
  klangrausch_network_development:
    ipam:
      driver: default
      config:
        - subnet: 172.16.77.0/24
