version: "3"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/


  klangrausch_django:
    build:
      context: ../django/
      dockerfile: django.development.Dockerfile
    env_file:
      - .env.klangrausch_django
    volumes:
      - ../django/klangrausch/:/klangrausch/
    command: gunicorn klangrausch.wsgi:application -b 0.0.0.0:8000
  

  klangrausch_postgresql:
    image: postgres:11-alpine
    env_file:
      - .env.klangrausch_postgresql

  
  klangrausch_gulp:
    build:
      context: ../gulp/
      dockerfile: gulp.development.Dockerfile
    volumes:
      - ../gulp/klangrausch/:/klangrausch/ # gulpfile
      - ../statifiles/css/:/staticfiles/css/
      - ../statifiles/js/:/statifiles/js/
      - ../statifiles/img/:/statifiles/img/
    command: watch
