version: "3"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/


  klangrausch_django:
    build:
      context: ../django/
      dockerfile: django.development.Dockerfile
    env_file:
      - .env.klangrausch_django
    volumes:
      - ../django/klangrausch/:/klangrausch/
    command: uvicorn klangrausch.asgi:application --host 0.0.0.0
  

  klangrausch_postgresql:
    image: postgres:11-alpine
    env_file:
      - .env.klangrausch_postgresql
