version: "3"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/


  klangrausch_django:
    image: django_alpine:2.2.5
    env_file:
      - .env.klangrausch_django
    volumes:
      - ../django/klangrausch/:/klangrausch/
    command: gunicorn klangrausch.wsgi:application -b 0.0.0.0:8000
  

  klangrausch_postgresql:
    image: postgres:11-alpine
    env_file:
      - .env.klangrausch_postgresql


  klangrausch_gulp:
    image: gulp_node_alpine:10.16.3
    volumes:
      - ../gulp/klangrausch/:/klangrausch/
      - ../statifiles/css/:/staticfiles/css/
      - ../statifiles/js/:/staticfiles/js/
      - ../statifiles/img/:/staticfiles/img/
