version: "3"

services:

  klangrausch_nginx:
    build:
      context: ../nginx/
      dockerfile: nginx.development.Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/conf.d/:/etc/nginx/conf.d/


  klangrausch_django:
    build:
      context: ../django/
      dockerfile: django.development.Dockerfile
    env_file:
      - .env.klangrausch_django
    volumes:
      - ../django/klangrausch/:/klangrausch/
    command: gunicorn klangrausch.wsgi:application -b 0.0.0.0:8000
    # networks:
    #   klangrausch_network_development:
    #     ipv4_address: 172.16.77.12
    #
  
  klangrausch_postgresql:
    image: postgres:11-alpine
    env_file:
      - .env.klangrausch_postgresql
    # networks:
    #   klangrausch_network_development:
    #     ipv4_address: 172.16.77.13


networks:
  klangrausch_network_development:
    ipam:
      driver: default
      config:
        - subnet: "172.16.77.0/24"
