version: "3.9"

services:

  # klangrausch_nginx:
  #   build:
  #     context: ../nginx/
  #     dockerfile: nginx.development.Dockerfile
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ../nginx/conf.d/:/etc/nginx/conf.d/
  #     - ../staticfiles/:/staticfiles/
  #

  klangrausch_django:
    image: django_4.2.14_alpine3.18:python_3.10.12
    ports:
      - "80:8000"
    env_file:
      - .env.klangrausch
    volumes:
      - ../django/klangrausch/:/klangrausch/
      - ../staticfiles/:/staticfiles/
    command: python manage.py runserver 0.0.0.0:8000
  

  klangrausch_postgresql:
    image: postgres:alpine3.17
    env_file:
      - .env.klangrausch
  
